### PR TITLE
Reworked sponsor footer

### PR DESCRIPTION
**Pull request by silkine**
Refactored sponsor page code, restructured md post files, updated all new sponsors

### CODE REVIEW

**Comment by cramforce** [comment]
Happy to merge at your request. And give you permission to merge :)

**Comment by silkine** [comment]
YAY! With great power comes great responsibility! I'm going to make it all
pink! Wait, it *is* pink :) OK Thx!

Malte Ubl <notifications@github.com> schrieb am Mi., 19. Apr. 2017 um
19:38 Uhr:

**Comment by cramforce** [comment]
Sent you invite link for write access.

**Comment by Kriesse** [comment]
Gave it a test run, looks and works beautifully 👏  Please merge @silkine :)

**Review by Kriesse — APPROVED** [review]

**Pull request merged**
