### PR TITLE
New sponsor footer

### PR DESCRIPTION
**Pull request by silkine**
# Reworked sponsor footer

- created a tiled sponsor list
- grouped sponsors by sponsor level
- added h3s for sponsor groups
- adjusted size of sponsor tiles according to sponsor level
- 2 tiles / row for mobile view for "supporting" and "other" sponsors
- replaced png logos with svgs

## **Note**:

all future logos must be SVG (because of css `height: 100%; width: 100%;`) PNGs will get distorted. Furthermore, all SVGs need `viewBox` attribute and `height` and `width` attribute inside their `<svg>` Tag.

### CODE REVIEW

**Comment by cramforce** [comment]
Thanks. I'll, uhm, merge this, and will then take a look locally.

**Comment by cramforce** [comment]
Looks great! Do you have the info to update this (partially) to the 2017 state?

**Comment by silkine** [comment]
Thanks! Not just yet, no. I can update the state as soon as I know, what to change. I can also help find the logos as SVG, as far as we don't get them from the companies. I'll have time for this starting Monday.

**Comment by cramforce** [comment]
@hblank should have the names. I think it would be cool to just publish more logos as we get them.

**Pull request merged**
